project:
  type: website
  output-dir: docs

execute:
  freeze: true
  cache: true
    
website:
  title: "Useful R Stuff"
  navbar:
    left:
      - href: http://www.aaronbraver.com
        text: Aaron Braver
    collapse-below: md
  google-analytics: "G-N1MBV4L3FV"

knitr  :
  opts_chunk:
    dev: ragg_png # use dev.args: {scaling: 0.5} chunk arg to scale

filters:
  - lightbox
lightbox:
  match: auto
  effect: fade

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    df-print: kable
    code-link: true
    code-annotations: hover
    
editor: source
