project:
  type: website
  output-dir: docs
  
author:
  name: "Aaron Braver"
  url: "https://www.aaronbraver.com"

execute:
  freeze: true
  cache: true
    
website:
  title: "Useful R Stuff"
  site-url: https://abraver.github.io/usefulRstuff
  navbar:
    left:
      - href: http://www.aaronbraver.com
        text: Aaron Braver
    right: 
      - icon: rss
        text: RSS
        href: index.xml
    collapse-below: md
  google-analytics: "G-N1MBV4L3FV"
  twitter-card: true
  open-graph: true

knitr  :
  opts_chunk:
    dev: ragg_png # use dev.args: {scaling: 0.5} chunk arg to scale

filters:
  - lightbox
lightbox:
  match: auto
  effect: fade

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    df-print: kable
    code-link: true
    code-annotations: hover
    
editor: source
